repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: mixed-line-ending
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
